### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/traittypes#24]
@vidartf I could check that the latest changes don't cause issues with xtensor.

Are you fine with me releasing or do you want to squeeze anything else before?

**Comment by vidartf** [comment]
With #23 in, I was able to rebase ipydatawidgets on traittypes locally, so I'm happy 👍

**Comment by SylvainCorlay** [comment]
Awesome!

I have just released traittypes 0.2.0, and the conda-forge package is building.
