### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/traittypes#9]
Using this space for a provisional roadmap on traittypes
1. `to_json` and `from_json` functions for ipywidgets with proposed implementation of javascript side counterparts.
2. `element_set` / `element_del` events.

**Comment by dmadeka** [comment]
Have we considered a CSS Dict trait type? Which makes the values of every key, a valid `CaselessStrEnum` which is valid for that CSS field

**Comment by SylvainCorlay** [comment]
@hainm opened issue https://github.com/ipython/ipywidgets/issues/740 to make css properties of layout Enums.
@dmadeka do you want to give it a shot?

**Comment by SylvainCorlay** [comment]
Closing as outdated.
